import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
export type Language = "en" | "hi" | "te";
export const languageOptions = [
  { value: "en", label: "English" },
  { value: "hi", label: "हिन्दी" },
  { value: "te", label: "తెలుగు" },
] as const;
type Catalog = Record<string, string>;
const hi: Catalog = { Temples:"मंदिर", Mandapas:"मंडप", Garbhagrihas:"गर्भगृह", Iconography:"प्रतिमा-विज्ञान", "Begin journey":"यात्रा शुरू करें", "Primary navigation":"मुख्य नेविगेशन", "Open navigation":"नेविगेशन खोलें", "Close navigation":"नेविगेशन बंद करें", Gallery:"गैलरी", "Indian Temples":"भारतीय मंदिर", "India’s living sacred landscapes":"भारत के जीवंत पवित्र दृश्य", "Explore the collection":"संग्रह देखें", "Scroll to enter":"प्रवेश के लिए स्क्रॉल करें", "A photographic field archive":"एक फोटोग्राफिक फील्ड आर्काइव", "The collection":"संग्रह", "Not monuments alone—":"केवल स्मारक नहीं—", "living cultural worlds.":"जीवंत सांस्कृतिक संसार।", "Select a path":"एक मार्ग चुनें", Temple:"मंदिर", index:"सूचकांक", "Filter the archive":"आर्काइव फ़िल्टर करें", "All states":"सभी राज्य", "All deities":"सभी देवता", "All styles":"सभी शैलियाँ", "Tamil Nadu":"तमिलनाडु", Odisha:"ओडिशा", Uttarakhand:"उत्तराखंड", "Meenakshi & Sundareswarar":"मीनाक्षी और सुंदरेश्वर", Surya:"सूर्य", Shiva:"शिव", Dravidian:"द्रविड़", Kalinga:"कलिंग", "Himalayan stone tradition":"हिमालयी पत्थर परंपरा", "A note on the archive":"आर्काइव पर एक टिप्पणी", "Built for looking":"देखने के लिए बना", "with care.":"सावधानी से।", "View image credits":"चित्र श्रेय देखें", "Image credit":"चित्र श्रेय", "The archives":"आर्काइव", "Architectural heritage":"स्थापत्य विरासत", "Vedic studies":"वैदिक अध्ययन", "Preserving the sacred silence through a living visual archive.":"जीवंत दृश्य आर्काइव के माध्यम से पवित्र मौन को संरक्षित करना।", "Back to temples":"मंदिरों पर लौटें", "Enter archive":"आर्काइव में प्रवेश करें", "Archive entry in preparation":"आर्काइव प्रविष्टि तैयार हो रही है", "Read the study":"अध्ययन पढ़ें", "The pillar halls":"स्तंभ मंडप", "The hierarchy of halls":"मंडपों का क्रम", "Main hall":"मुख्य मंडप", Pavilion:"मंडपिका", "Ante-chamber":"अंतर-कक्ष", "The Garbhagrihas":"गर्भगृह", "I. The inner room":"I. आंतरिक कक्ष", "Where the temple":"जहाँ मंदिर", "becomes still.":"शांत हो जाता है।", "Stone, shadow, threshold":"पत्थर, छाया, देहरी", "Architectural marvel":"स्थापत्य चमत्कार", "The eternal flame":"शाश्वत ज्योति", "Return to the archive":"आर्काइव पर लौटें", "Explore the temple gallery":"मंदिर गैलरी देखें", Meenakshi:"मीनाक्षी", Amman:"अम्मन", "I. The Divine Presence":"I. दिव्य उपस्थिति", "Sacred architecture":"पवित्र स्थापत्य", "III. Ritual & Ornamentation":"III. अनुष्ठान और अलंकरण", "The Thirukalyanam":"तिरुकल्याणम", "Continue the archive":"आर्काइव जारी रखें", "Return to Indian temples":"भारतीय मंदिरों पर लौटें", "Page Not Found":"पृष्ठ नहीं मिला", "Go Home":"होम पर जाएँ", "No entries meet this combination. Try a wider path through the archive.":"इस संयोजन से कोई प्रविष्टि नहीं मिली।", "Filter by state":"राज्य के अनुसार फ़िल्टर", "Filter by deity":"देवता के अनुसार फ़िल्टर", "Filter by style":"शैली के अनुसार फ़िल्टर", Language:"भाषा", "The":"यह", "Sacred":"पवित्र", architecture:"स्थापत्य", "Adornment as":"उपस्थिति के रूप में", "an act of presence.":"अलंकरण।", "Follow the stones":"पत्थरों के साथ चलें", "into the":"प्रवेश करें", "collection.":"संग्रह में।", "marvel":"चमत्कार", "Light held":"प्रकाश ठहरा", "in the dark.":"अंधकार में।", "Experience the":"अनुभव करें", "sanctum.":"गर्भगृह।" };
const te: Catalog = { Temples:"ఆలయాలు", Mandapas:"మండపాలు", Garbhagrihas:"గర్భగృహాలు", Iconography:"ప్రతిమాశాస్త్రం", "Begin journey":"ప్రయాణం ప్రారంభించండి", "Primary navigation":"ప్రధాన నావిగేషన్", "Open navigation":"నావిగేషన్ తెరవండి", "Close navigation":"నావిగేషన్ మూసివేయండి", Gallery:"గ్యాలరీ", "Indian Temples":"భారతీయ ఆలయాలు", "India’s living sacred landscapes":"భారతదేశపు జీవంతమైన పవిత్ర దృశ్యాలు", "Explore the collection":"సేకరణను చూడండి", "Scroll to enter":"ప్రవేశించడానికి స్క్రోల్ చేయండి", "A photographic field archive":"ఒక ఫోటోగ్రాఫిక్ ఫీల్డ్ ఆర్కైవ్", "The collection":"సేకరణ", "Not monuments alone—":"కేవలం స్మారకాలు కాదు—", "living cultural worlds.":"జీవంతమైన సాంస్కృతిక ప్రపంచాలు.", "Select a path":"ఒక మార్గాన్ని ఎంచుకోండి", Temple:"ఆలయం", index:"సూచిక", "Filter the archive":"ఆర్కైవ్‌ను వడపోసండి", "All states":"అన్ని రాష్ట్రాలు", "All deities":"అన్ని దేవతలు", "All styles":"అన్ని శైలులు", "Tamil Nadu":"తమిళనాడు", Odisha:"ఒడిశా", Uttarakhand:"ఉత్తరాఖండ్", "Meenakshi & Sundareswarar":"మీనాక్షి మరియు సుందరేశ్వరుడు", Surya:"సూర్యుడు", Shiva:"శివుడు", Dravidian:"ద్రావిడ", Kalinga:"కళింగ", "Himalayan stone tradition":"హిమాలయ రాతి సంప్రదాయం", "A note on the archive":"ఆర్కైవ్‌పై ఒక గమనిక", "Built for looking":"చూడటానికి నిర్మించబడింది", "with care.":"శ్రద్ధతో।", "View image credits":"చిత్ర క్రెడిట్‌లను చూడండి", "Image credit":"చిత్ర క్రెడిట్", "The archives":"ఆర్కైవ్‌లు", "Architectural heritage":"నిర్మాణ వారసత్వం", "Vedic studies":"వేద అధ్యయనాలు", "Preserving the sacred silence through a living visual archive.":"జీవంతమైన దృశ్య ఆర్కైవ్ ద్వారా పవిత్ర నిశ్శబ్దాన్ని సంరక్షించడం.", "Back to temples":"ఆలయాలకు తిరిగి వెళ్లండి", "Enter archive":"ఆర్కైవ్‌లోకి ప్రవేశించండి", "Archive entry in preparation":"ఆర్కైవ్ నమోదు సిద్ధమవుతోంది", "Read the study":"అధ్యయనాన్ని చదవండి", "The pillar halls":"స్తంభ మండపాలు", "The hierarchy of halls":"మండపాల క్రమం", "Main hall":"ప్రధాన మండపం", Pavilion:"మండపిక", "Ante-chamber":"ముందరి గది", "The Garbhagrihas":"గర్భగృహాలు", "I. The inner room":"I. అంతర్గత గది", "Where the temple":"ఆలయం ఎక్కడ", "becomes still.":"నిశ్చలమవుతుంది।", "Stone, shadow, threshold":"రాయి, నీడ, గడప", "Architectural marvel":"నిర్మాణ అద్భుతం", "The eternal flame":"శాశ్వత జ్వాల", "Return to the archive":"ఆర్కైవ్‌కు తిరిగి వెళ్లండి", "Explore the temple gallery":"ఆలయ గ్యాలరీని చూడండి", Meenakshi:"మీనాక్షి", Amman:"అమ్మన్", "I. The Divine Presence":"I. దైవిక ఉనికి", "Sacred architecture":"పవిత్ర నిర్మాణం", "III. Ritual & Ornamentation":"III. ఆచారం మరియు అలంకరణ", "The Thirukalyanam":"తిరుకల్యాణం", "Continue the archive":"ఆర్కైవ్‌ను కొనసాగించండి", "Return to Indian temples":"భారతీయ ఆలయాలకు తిరిగి వెళ్లండి", "Page Not Found":"పేజీ కనబడలేదు", "Go Home":"హోమ్‌కు వెళ్లండి", "No entries meet this combination. Try a wider path through the archive.":"ఈ కలయికకు నమోదులు లేవు.", "Filter by state":"రాష్ట్రం ప్రకారం వడపోసండి", "Filter by deity":"దేవత ప్రకారం వడపోసండి", "Filter by style":"శైలి ప్రకారం వడపోసండి", Language:"భాష", "The":"ఈ", "Sacred":"పవిత్ర", architecture:"నిర్మాణం", "Adornment as":"ఉనికిగా", "an act of presence.":"అలంకరణ.", "Follow the stones":"రాళ్ల వెంట నడవండి", "into the":"లోకి", "collection.":"సేకరణ.", "marvel":"అద్భుతం", "Light held":"వెలుగు నిలిచింది", "in the dark.":"చీకటిలో.", "Experience the":"అనుభవించండి", "sanctum.":"గర్భగృహాన్ని." };
	const hiExtra: Catalog = {
	  "An evolving visual archive · Edition 01": "एक विकसित होता दृश्य आर्काइव · संस्करण 01",
	  "A visual index of structures shaped by devotion, geometry, craftsmanship, and the long memory of place.": "भक्ति, ज्यामिति, शिल्प और स्थान की दीर्घ स्मृति से आकार पाई संरचनाओं का दृश्य सूचकांक।",
	  "Filter the first three entries by regional setting, principal deity, or architectural tradition.": "पहली तीन प्रविष्टियों को क्षेत्र, प्रमुख देवता या स्थापत्य परंपरा के अनुसार फ़िल्टर करें।",
	  "Photography in this prototype is sourced from reusable Wikimedia Commons files and linked back to its original credit record.": "इस प्रोटोटाइप की तस्वीरें पुनः उपयोग योग्य Wikimedia Commons फ़ाइलों से ली गई हैं और उनके मूल श्रेय रिकॉर्ड से जुड़ी हैं।",
	  "Eternal Heritage home": "Eternal Heritage होम",
	  "A living temple city where devotion, water, sculpture, and monumental gateways compose the historic heart of Madurai.": "एक जीवंत मंदिर-नगरी जहाँ भक्ति, जल, शिल्प और विशाल प्रवेश-द्वार मदुरै के ऐतिहासिक हृदय को रचते हैं।",
	  "Madurai, Tamil Nadu · Archive / 01": "मदुरै, तमिलनाडु · आर्काइव / 01",
	  "A visual field guide to a living sacred complex": "एक जीवंत पवित्र परिसर के लिए दृश्य फील्ड गाइड",
	  "At the center of": "के केंद्र में",
	  "Madurai’s memory.": "मदुरै की स्मृति।",
	  "Meenakshi voice explanation": "मदुरै का मीनाक्षी अम्मन मंदिर मीनाक्षी और सुंदरेश्वर को समर्पित एक जीवंत पवित्र नगर है। इसके ऊँचे गोपुरम, मंदिर सरोवर, नक्काशीदार मंडप और जुलूस मार्ग तमिलनाडु की दैनिक पूजा और उत्सवों से आकार लेते हैं।",
	  "Thousand Pillar Hall · Madurai Meenakshi Temple": "सहस्र स्तंभ मंडप · मदुरै मीनाक्षी मंदिर",
	  "Sculptural detail · Meenakshi Amman Temple": "शिल्प विवरण · मीनाक्षी अम्मन मंदिर",
	  "The Mandalas": "मंडल",
	  "The temple is experienced as a sequence of nested thresholds: tank, courtyards, halls, shrines, and processional paths. Geometry here is lived through movement rather than encountered as an abstract diagram.": "मंदिर का अनुभव एक के भीतर एक स्थित देहरियों के क्रम के रूप में होता है: सरोवर, आँगन, मंडप, देवालय और जुलूस मार्ग। यहाँ ज्यामिति किसी अमूर्त चित्र की तरह नहीं, बल्कि गति के माध्यम से जी जाती है।",
	  "The Gopurams": "गोपुरम",
	  "Its gateway towers act as visible orientation points across the city. Their sculptural surfaces turn ascent into a dense public field of stories, guardians, and celestial figures.": "इसके प्रवेश-द्वार मीनारें पूरे नगर में दिशा-सूचक बिंदु का काम करती हैं। उनकी शिल्प-सतहें आरोहण को कथाओं, रक्षकों और आकाशीय आकृतियों के सघन सार्वजनिक संसार में बदल देती हैं।",
	  "Aiyram Kaal": "आयिरम काल",
	  "The Thousand Pillar Hall is celebrated for its ordered forest of carved supports. The name describes a civic scale of gathering, craft, and visual rhythm rather than a single isolated monument.": "सहस्र स्तंभ मंडप अपने क्रमबद्ध नक्काशीदार स्तंभों के वन के लिए प्रसिद्ध है। यह नाम किसी अकेले स्मारक से अधिक सभा, शिल्प और दृश्य लय के नागरिक विस्तार को दर्शाता है।",
	  "Architectural marvels · Archive / 02": "स्थापत्य चमत्कार · आर्काइव / 02",
	  "Enter the halls of assembly, where processional movement, crafted stone, and shared ceremony give architecture its social life.": "सभा के मंडपों में प्रवेश करें, जहाँ जुलूस की गति, तराशा हुआ पत्थर और सामूहिक अनुष्ठान स्थापत्य को उसका सामाजिक जीवन देते हैं।",
	  "Ayiram Kaal Mandapam · Madurai": "आयिरम काल मंडप · मदुरै",
	  "I. Architectural Marvels": "I. स्थापत्य चमत्कार",
	  "Mandapas are the expansive, columned rooms that make the temple a place of assembly. They absorb the scale of festivals and daily passage, while offering a deliberate transition toward more restricted inner spaces.": "मंडप विस्तृत स्तंभित कक्ष हैं जो मंदिर को सभा का स्थान बनाते हैं। वे उत्सवों और दैनिक आवागमन का विस्तार समेटते हैं और भीतर के अधिक सीमित स्थानों की ओर एक विचारपूर्ण संक्रमण देते हैं।",
	  "Their visual force lies in recurrence. One support leads to another; open bays frame fragments of light; intricate carving keeps the eye moving even as the body slows.": "उनका दृश्य प्रभाव पुनरावृत्ति में है। एक स्तंभ दूसरे तक ले जाता है; खुले खंड प्रकाश के अंशों को चौखटा देते हैं; सूक्ष्म नक्काशी शरीर के ठहरने पर भी आँखों को गतिमान रखती है।",
	  "II. A field note from Madurai": "II. मदुरै से एक फील्ड नोट",
	  "A study in density, repetition, and the visual tempo of stone.": "घनत्व, पुनरावृत्ति और पत्थर की दृश्य गति का अध्ययन।",
	  "Pillar as presence": "उपस्थिति के रूप में स्तंभ",
	  "Columns in a mandapa are more than supports. Their repeated spacing sets a rhythm for movement, gathering, and the gradual reading of carved surfaces.": "मंडप के स्तंभ केवल सहारे नहीं हैं। उनकी दोहराई गई दूरी गति, सभा और नक्काशीदार सतहों को धीरे-धीरे पढ़ने की लय बनाती है।",
	  "A measured pause": "एक मापी हुई ठहराव",
	  "The hall creates a shared interval between public court and inner shrine—a place where festivals, music, processions, and quiet waiting can take shape.": "मंडप सार्वजनिक प्रांगण और भीतरी देवालय के बीच साझा अंतराल बनाता है—एक ऐसा स्थान जहाँ उत्सव, संगीत, जुलूस और शांत प्रतीक्षा आकार ले सकते हैं।",
	  "Carved encounter": "नक्काशी से साक्षात्कार",
	  "Close looking rewards the visitor: animal guardians, figures, and ornamental details animate the stone and make architectural scale feel intimate.": "ध्यान से देखना आगंतुक को पुरस्कृत करता है: पशु रक्षक, आकृतियाँ और अलंकरण पत्थर को जीवंत बनाते हैं और स्थापत्य के विस्तार को आत्मीय बना देते हैं।",
	  "Wayfinding in stone": "पत्थर में दिशा-बोध",
	  "The order of the hall offers orientation without signage, guiding the visitor through structural rhythm and framed sightlines.": "मंडप का क्रम बिना संकेत-पटों के दिशा देता है और आगंतुक को संरचनात्मक लय तथा चौखटे में बंधे दृश्यों के माध्यम से आगे ले जाता है।",
	  "A corridor toward the mandapa": "मंडप की ओर जाता गलियारा",
	  "The hierarchy of": "का क्रम",
	  halls: "मंडप",
	  "The larger public hall, where the approach slows and the community gathers before the more focused spaces of worship.": "बड़ा सार्वजनिक मंडप, जहाँ पहुँचने की गति धीमी होती है और पूजा के अधिक केंद्रित स्थानों से पहले समुदाय एकत्र होता है।",
	  "A separate, often axial pavilion that becomes a visual and ceremonial hinge in a Shaiva temple complex.": "एक अलग, अक्सर अक्षीय मंडप जो शैव मंदिर परिसर में दृश्य और अनुष्ठानिक कड़ी बन जाता है।",
	  "The smaller transitional room that tunes attention before the threshold of the sanctum.": "छोटा संक्रमण कक्ष जो गर्भगृह की देहरी से पहले ध्यान को केंद्रित करता है।",
	  "The innermost chamber · Archive / 03": "सबसे भीतरी कक्ष · आर्काइव / 03",
	  "Step into the sacred heart of the temple: an architecture of enclosure, directed attention, and quiet ritual presence.": "मंदिर के पवित्र हृदय में प्रवेश करें: घेराव, केंद्रित ध्यान और शांत अनुष्ठानिक उपस्थिति का स्थापत्य।",
	  "II. A concentrated architecture": "II. एक केंद्रित स्थापत्य",
	  "Four ways to look closely at the small, potent core of a temple plan.": "मंदिर की योजना के छोटे, प्रभावशाली केंद्र को ध्यान से देखने के चार तरीके।",
	  "A nested threshold": "एक के भीतर एक देहरी",
	  "The sanctum is reached through a sequence of increasingly concentrated spaces. Architecture makes the act of approach tangible.": "गर्भगृह तक क्रमशः अधिक केंद्रित होते स्थानों की श्रृंखला से पहुँचा जाता है। स्थापत्य पहुँचने की क्रिया को मूर्त बना देता है।",
	  "The weight of stone": "पत्थर का भार",
	  "Its compact form and reduced light concentrate attention on mass, boundary, and the carved material of the shrine.": "इसका सघन रूप और कम प्रकाश ध्यान को भार, सीमा और देवालय की तराशी हुई सामग्री पर केंद्रित करते हैं।",
	  "Cosmic orientation": "ब्रह्मांडीय अभिमुखता",
	  "Temple planning connects spatial order to ritual direction, making the shrine a focused point within a larger sacred field.": "मंदिर की योजना स्थानिक क्रम को अनुष्ठानिक दिशा से जोड़ती है और देवालय को बड़े पवित्र क्षेत्र में एक केंद्रित बिंदु बनाती है।",
	  "The circumambulatory path": "प्रदक्षिणा पथ",
	  "Movement around the inner core gives the body a way to read stillness, repetition, and enclosure.": "भीतरी केंद्र के चारों ओर गति शरीर को स्थिरता, पुनरावृत्ति और घेराव को पढ़ने का तरीका देती है।",
	  "This page uses architectural studies rather than photographs of restricted ritual interiors.": "यह पृष्ठ प्रतिबंधित अनुष्ठानिक अंदरूनी भागों की तस्वीरों के बजाय स्थापत्य अध्ययनों का उपयोग करता है।",
	  "Within the visual culture of the temple, a lamp does more than illuminate. Its small circle of light marks a moment of attention, revealing surface slowly and allowing darkness to retain its depth.": "मंदिर की दृश्य संस्कृति में दीपक केवल प्रकाश नहीं देता। उसका छोटा प्रकाश-वृत्त ध्यान के एक क्षण को चिह्नित करता है, सतह को धीरे-धीरे प्रकट करता है और अंधकार की गहराई को बनाए रखता है।",
	  "Each entry follows a temple through the materials of its presence: landmark architecture, ritual circulation, carved surfaces, and the human histories carried in its setting. The first archive room opens in Madurai.": "हर प्रविष्टि मंदिर की उपस्थिति की सामग्री—प्रमुख स्थापत्य, अनुष्ठानिक आवागमन, नक्काशीदार सतहों और अपने परिवेश में संचित मानवीय इतिहास—के माध्यम से उसकी यात्रा करती है। पहला आर्काइव कक्ष मदुरै में खुलता है।",
	  "II. Architectural Field Notes": "II. स्थापत्य फील्ड नोट्स",
	  "III. Sequence and scale": "III. क्रम और विस्तार",
	  "III. The eternal flame": "III. शाश्वत ज्योति",
	  "It may have been moved or deleted.": "शायद इसे स्थानांतरित या हटा दिया गया है।",
	  "Meenakshi is revered as a form of Parvati, while Sundareswarar is Shiva in his local manifestation. Their paired shrines shape the temple’s devotional rhythm and its powerful sense of sacred reciprocity.": "मीनाक्षी को पार्वती का एक रूप माना जाता है, जबकि सुंदरेश्वर शिव का स्थानीय रूप हैं। उनके संयुक्त देवालय मंदिर की भक्ति-लय और पवित्र पारस्परिकता की गहरी अनुभूति को आकार देते हैं।",
	  "Ornament is not simply surface at Meenakshi. Colour, metal, flowers, textiles, and illuminated stone make ritual visible—reframing the temple’s architecture for each occasion while retaining its enduring spatial order.": "मीनाक्षी में अलंकरण केवल सतह नहीं है। रंग, धातु, फूल, वस्त्र और प्रकाशित पत्थर अनुष्ठान को दृश्य बनाते हैं—हर अवसर पर मंदिर के स्थापत्य को नया रूप देते हुए भी उसके स्थायी स्थानिक क्रम को बनाए रखते हैं।",
	  "Sorry, the page you are looking for doesn't exist.": "क्षमा करें, आप जिस पृष्ठ को खोज रहे हैं वह मौजूद नहीं है।",
	  "The ceremonial wedding of Meenakshi and Sundareswarar is the emotional high point of the Chithirai festival. It gathers theology, music, dress, procession, and public participation into a single seasonal event.": "मीनाक्षी और सुंदरेश्वर का औपचारिक विवाह चिथिरई उत्सव का भावनात्मक शिखर है। यह धर्मशास्त्र, संगीत, वेशभूषा, जुलूस और जन-भागीदारी को एक मौसमी आयोजन में समेटता है।",
	  "The complex is best read as a sequence of thresholds, towers, circulation, and crafted stone—an architecture continually renewed by use.": "इस परिसर को देहरियों, मीनारों, आवागमन और तराशे हुए पत्थर के क्रम के रूप में पढ़ना सबसे उचित है—एक ऐसा स्थापत्य जो उपयोग से निरंतर नया होता रहता है।",
	  "The experience is architectural as much as spiritual: passages gather into halls, filtered light falls across stone, and the complex unfolds through ceremony, study, commerce, and return.": "यह अनुभव आध्यात्मिक जितना ही स्थापत्य का भी है: गलियारे मंडपों में मिलते हैं, छनकर आती रोशनी पत्थर पर पड़ती है और परिसर समारोह, अध्ययन, व्यापार और वापसी के माध्यम से खुलता जाता है।",
	  "The experience shifts at the threshold. Light is reduced, sound is gathered, and the elaborate narratives of the exterior fall away in favour of a more concentrated encounter.": "देहरी पर अनुभव बदल जाता है। प्रकाश कम हो जाता है, ध्वनि एकत्र होती है और बाहरी भाग की विस्तृत कथाएँ एक अधिक केंद्रित साक्षात्कार के लिए पीछे हट जाती हैं।",
	  "The garbhagriha, literally the “womb chamber,” is the spatial core of a Hindu temple. Its deliberately contained scale gives the structure a gravitational center—one that anchors larger halls, gateways, and routes of circulation.": "गर्भगृह, जिसका शाब्दिक अर्थ ‘गर्भ कक्ष’ है, हिंदू मंदिर का स्थानिक केंद्र है। इसका जानबूझकर सीमित विस्तार संरचना को गुरुत्व-केंद्र देता है—जो बड़े मंडपों, प्रवेश-द्वारों और आवागमन मार्गों को आधार देता है।",
	  "Listen to this place": "इस स्थान के बारे में सुनें",
	  "Stop listening": "सुनना रोकें",
	  Listen: "सुनें",
	  Stop: "रोकें",
	  "Voice guidance is not available in this browser": "इस ब्राउज़र में वॉइस गाइड उपलब्ध नहीं है",
	  "Meenakshi Amman": "मीनाक्षी अम्मन",
	  "Madurai, Tamil Nadu": "मदुरै, तमिलनाडु",
	  "Konark, Odisha": "कोणार्क, ओडिशा",
	  "Rudraprayag, Uttarakhand": "रुद्रप्रयाग, उत्तराखंड",
	  "Konark Sun Temple": "कोणार्क सूर्य मंदिर",
	  Kedarnath: "केदारनाथ",
	  "A vast sacred complex shaped by gopurams, water, processional routes, and the continuing ritual life of Madurai.": "गोपुरमों, जल, जुलूस मार्गों और मदुरै के निरंतर अनुष्ठानिक जीवन से आकार पाया विशाल पवित्र परिसर।",
	  "A monumental thirteenth-century temple known for its sculptural stonework and chariot-like cosmological form.": "तेरहवीं शताब्दी का विशाल मंदिर, जो अपनी शिल्पित पत्थर-कला और रथ जैसी ब्रह्मांडीय आकृति के लिए प्रसिद्ध है।",
	  "A high Himalayan shrine whose compact stone architecture is framed by the severe scale of the Garhwal mountains.": "एक ऊँचा हिमालयी देवालय जिसकी सघन पत्थर वास्तुकला गढ़वाल पर्वतों के विराट विस्तार से घिरी है।",
	  "A towering gopuram at the Meenakshi Amman Temple in Madurai.": "मदुरै के मीनाक्षी अम्मन मंदिर का ऊँचा गोपुरम।",
	  "The stone mass of the Konark Sun Temple under a deep blue night sky.": "गहरे नीले रात्रि आकाश के नीचे कोणार्क सूर्य मंदिर का पत्थरीला विस्तार।",
	  "Kedarnath Temple set beneath rocky Himalayan slopes.": "पथरीली हिमालयी ढलानों के नीचे स्थित केदारनाथ मंदिर।",
	};
	const teExtra: Catalog = {
	  "An evolving visual archive · Edition 01": "పెరుగుతున్న దృశ్య ఆర్కైవ్ · సంచిక 01",
	  "A visual index of structures shaped by devotion, geometry, craftsmanship, and the long memory of place.": "భక్తి, జ్యామితి, శిల్పకళ మరియు స్థలపు దీర్ఘ స్మృతితో రూపుదిద్దుకున్న నిర్మాణాల దృశ్య సూచిక.",
	  "Filter the first three entries by regional setting, principal deity, or architectural tradition.": "మొదటి మూడు నమోదులను ప్రాంతం, ప్రధాన దేవత లేదా నిర్మాణ సంప్రదాయం ప్రకారం వడపోసండి.",
	  "Photography in this prototype is sourced from reusable Wikimedia Commons files and linked back to its original credit record.": "ఈ నమూనాలోని చిత్రాలు పునర్వినియోగించగల Wikimedia Commons ఫైళ్ల నుండి తీసుకోబడ్డాయి మరియు వాటి మూల క్రెడిట్ రికార్డుకు అనుసంధానించబడ్డాయి.",
	  "Eternal Heritage home": "Eternal Heritage హోమ్",
	  "A living temple city where devotion, water, sculpture, and monumental gateways compose the historic heart of Madurai.": "భక్తి, నీరు, శిల్పం మరియు మహత్తర గోపురాలు మదురై చారిత్రక హృదయాన్ని నిర్మించే జీవంతమైన ఆలయ నగరం.",
	  "Madurai, Tamil Nadu · Archive / 01": "మదురై, తమిళనాడు · ఆర్కైవ్ / 01",
	  "A visual field guide to a living sacred complex": "జీవంతమైన పవిత్ర సముదాయానికి దృశ్య ఫీల్డ్ గైడ్",
	  "At the center of": "కేంద్రంలో",
	  "Madurai’s memory.": "మదురై జ్ఞాపకం.",
	  "Meenakshi voice explanation": "మదురైలోని మీనాక్షి అమ్మన్ ఆలయం మీనాక్షి మరియు సుందరేశ్వరుడికి అంకితమైన జీవంతమైన పవిత్ర నగరం. దాని ఎత్తైన గోపురాలు, ఆలయ కొలను, చెక్కిన మండపాలు మరియు ఊరేగింపు మార్గాలు తమిళనాడు దైనందిన పూజలు మరియు పండుగలతో రూపుదిద్దుకుంటాయి.",
	  "Thousand Pillar Hall · Madurai Meenakshi Temple": "వెయ్యి స్తంభాల మండపం · మదురై మీనాక్షి ఆలయం",
	  "Sculptural detail · Meenakshi Amman Temple": "శిల్ప వివరాలు · మీనాక్షి అమ్మన్ ఆలయం",
	  "The Mandalas": "మండలాలు",
	  "The temple is experienced as a sequence of nested thresholds: tank, courtyards, halls, shrines, and processional paths. Geometry here is lived through movement rather than encountered as an abstract diagram.": "ఆలయ అనుభవం ఒకదానిలో మరొకటి ఉన్న గడపల క్రమంగా ఉంటుంది: కొలను, ప్రాంగణాలు, మండపాలు, ఆలయాలు మరియు ఊరేగింపు మార్గాలు. ఇక్కడ జ్యామితి ఒక సారాంశ చిత్రంగా కాకుండా కదలిక ద్వారా జీవించబడుతుంది.",
	  "The Gopurams": "గోపురాలు",
	  "Its gateway towers act as visible orientation points across the city. Their sculptural surfaces turn ascent into a dense public field of stories, guardians, and celestial figures.": "దాని ప్రవేశ గోపురాలు నగరమంతా దిశను చూపే గుర్తులుగా ఉంటాయి. వాటి శిల్ప ఉపరితలాలు ఎక్కింపును కథలు, రక్షకులు మరియు ఆకాశీయ రూపాల సాంద్రమైన ప్రజా ప్రపంచంగా మారుస్తాయి.",
	  "Aiyram Kaal": "ఆయిరం కాళ్",
	  "The Thousand Pillar Hall is celebrated for its ordered forest of carved supports. The name describes a civic scale of gathering, craft, and visual rhythm rather than a single isolated monument.": "వెయ్యి స్తంభాల మండపం క్రమబద్ధంగా చెక్కిన స్తంభాల అరణ్యానికి ప్రసిద్ధి. ఈ పేరు ఒక ఒంటరి స్మారకాన్ని కాకుండా సమాగమం, శిల్పం మరియు దృశ్య లయ యొక్క సామాజిక విస్తృతిని వివరిస్తుంది.",
	  "Architectural marvels · Archive / 02": "నిర్మాణ అద్భుతాలు · ఆర్కైవ్ / 02",
	  "Enter the halls of assembly, where processional movement, crafted stone, and shared ceremony give architecture its social life.": "ఊరేగింపు కదలిక, చెక్కిన రాయి మరియు సామూహిక ఆచారం నిర్మాణానికి సామాజిక జీవాన్ని ఇచ్చే సభా మండపాల్లోకి ప్రవేశించండి.",
	  "Ayiram Kaal Mandapam · Madurai": "ఆయిరం కాళ్ మండపం · మదురై",
	  "I. Architectural Marvels": "I. నిర్మాణ అద్భుతాలు",
	  "Mandapas are the expansive, columned rooms that make the temple a place of assembly. They absorb the scale of festivals and daily passage, while offering a deliberate transition toward more restricted inner spaces.": "మండపాలు ఆలయాన్ని సమాగమ స్థలంగా మార్చే విశాలమైన స్తంభాల గదులు. అవి పండుగలు మరియు దైనందిన రాకపోకల విస్తృతిని మోస్తూ, మరింత పరిమితమైన అంతర్గత ప్రదేశాల వైపు ఆలోచనాత్మక మార్గాన్ని అందిస్తాయి.",
	  "Their visual force lies in recurrence. One support leads to another; open bays frame fragments of light; intricate carving keeps the eye moving even as the body slows.": "వాటి దృశ్య శక్తి పునరావృతిలో ఉంది. ఒక స్తంభం మరొకదానికి దారి చూపుతుంది; తెరచిన భాగాలు కాంతి ముక్కలను ఫ్రేమ్ చేస్తాయి; సూక్ష్మమైన చెక్కడం శరీరం నెమ్మదించినా చూపును కదిలిస్తుంది.",
	  "II. A field note from Madurai": "II. మదురై నుండి ఒక ఫీల్డ్ నోట్",
	  "A study in density, repetition, and the visual tempo of stone.": "సాంద్రత, పునరావృతం మరియు రాయి దృశ్య లయపై అధ్యయనం.",
	  "Pillar as presence": "ఉనికిగా స్తంభం",
	  "Columns in a mandapa are more than supports. Their repeated spacing sets a rhythm for movement, gathering, and the gradual reading of carved surfaces.": "మండపంలోని స్తంభాలు కేవలం ఆధారాలు కావు. వాటి పునరావృత అంతరం కదలిక, సమాగమం మరియు చెక్కిన ఉపరితలాలను క్రమంగా చదివే లయను ఏర్పరుస్తుంది.",
	  "A measured pause": "కొలిచిన విరామం",
	  "The hall creates a shared interval between public court and inner shrine—a place where festivals, music, processions, and quiet waiting can take shape.": "మండపం బహిరంగ ప్రాంగణం మరియు అంతర్గత ఆలయం మధ్య పంచుకున్న విరామాన్ని సృష్టిస్తుంది—పండుగలు, సంగీతం, ఊరేగింపులు మరియు నిశ్శబ్ద నిరీక్షణ రూపం దాల్చే స్థలం.",
	  "Carved encounter": "చెక్కిన రాయితో సాక్షాత్కారం",
	  "Close looking rewards the visitor: animal guardians, figures, and ornamental details animate the stone and make architectural scale feel intimate.": "దగ్గరగా చూడటం సందర్శకుడికి ఫలితాన్నిస్తుంది: జంతు రక్షకులు, రూపాలు మరియు అలంకార వివరాలు రాయిని సజీవం చేసి నిర్మాణ పరిమాణాన్ని సన్నిహితంగా అనిపింపజేస్తాయి.",
	  "Wayfinding in stone": "రాయిలో దిశా బోధ",
	  "The order of the hall offers orientation without signage, guiding the visitor through structural rhythm and framed sightlines.": "మండప క్రమం ఎలాంటి సూచికలు లేకుండానే దిశను అందిస్తుంది; నిర్మాణ లయ మరియు ఫ్రేమ్ చేసిన దృశ్యాల ద్వారా సందర్శకుడిని నడిపిస్తుంది.",
	  "A corridor toward the mandapa": "మండపం వైపు వెళ్లే మార్గం",
	  "The hierarchy of": "క్రమం",
	  halls: "మండపాలు",
	  "The larger public hall, where the approach slows and the community gathers before the more focused spaces of worship.": "పెద్ద ప్రజా మండపం, అక్కడ చేరువ నెమ్మదించి, మరింత కేంద్రీకృతమైన పూజా స్థలాల ముందు సమాజం కూడుతుంది.",
	  "A separate, often axial pavilion that becomes a visual and ceremonial hinge in a Shaiva temple complex.": "వేరుగా ఉండే, తరచుగా అక్షీయంగా ఉన్న మండపం శైవ ఆలయ సముదాయంలో దృశ్య మరియు ఆచార కేంద్రమవుతుంది.",
	  "The smaller transitional room that tunes attention before the threshold of the sanctum.": "గర్భగృహం గడపకు ముందు దృష్టిని కేంద్రీకరించే చిన్న మార్పిడి గది.",
	  "The innermost chamber · Archive / 03": "అంతర్గత గది · ఆర్కైవ్ / 03",
	  "Step into the sacred heart of the temple: an architecture of enclosure, directed attention, and quiet ritual presence.": "ఆలయ పవిత్ర హృదయంలోకి అడుగు పెట్టండి: ఆవరణ, కేంద్రీకృత దృష్టి మరియు నిశ్శబ్ద ఆచార ఉనికి యొక్క నిర్మాణం.",
	  "II. A concentrated architecture": "II. కేంద్రీకృత నిర్మాణం",
	  "Four ways to look closely at the small, potent core of a temple plan.": "ఆలయ ప్రణాళికలోని చిన్న, శక్తివంతమైన కేంద్రాన్ని దగ్గరగా చూడటానికి నాలుగు మార్గాలు.",
	  "A nested threshold": "లోపలికి లోపల గడప",
	  "The sanctum is reached through a sequence of increasingly concentrated spaces. Architecture makes the act of approach tangible.": "క్రమంగా కేంద్రీకృతమయ్యే ప్రదేశాల శ్రేణి ద్వారా గర్భగృహాన్ని చేరుకుంటారు. నిర్మాణం చేరువయ్యే చర్యను స్పష్టంగా అనుభూతి చేయిస్తుంది.",
	  "The weight of stone": "రాయి బరువు",
	  "Its compact form and reduced light concentrate attention on mass, boundary, and the carved material of the shrine.": "దాని సాంద్రమైన రూపం మరియు తగ్గిన వెలుగు దృష్టిని పరిమాణం, సరిహద్దు మరియు ఆలయం చెక్కిన పదార్థంపై కేంద్రీకరిస్తాయి.",
	  "Cosmic orientation": "విశ్వ దిశానిర్దేశం",
	  "Temple planning connects spatial order to ritual direction, making the shrine a focused point within a larger sacred field.": "ఆలయ ప్రణాళిక స్థల క్రమాన్ని ఆచార దిశతో కలుపుతుంది; ఆలయాన్ని పెద్ద పవిత్ర క్షేత్రంలో కేంద్రీకృత బిందువుగా చేస్తుంది.",
	  "The circumambulatory path": "ప్రదక్షిణ మార్గం",
	  "Movement around the inner core gives the body a way to read stillness, repetition, and enclosure.": "అంతర్గత కేంద్రం చుట్టూ కదలిక శరీరానికి నిశ్చలత, పునరావృతం మరియు ఆవరణను చదివే మార్గాన్ని ఇస్తుంది.",
	  "This page uses architectural studies rather than photographs of restricted ritual interiors.": "ఈ పేజీ పరిమితమైన ఆచార అంతర్గతాల చిత్రాల బదులుగా నిర్మాణ అధ్యయనాలను ఉపయోగిస్తుంది.",
	  "Within the visual culture of the temple, a lamp does more than illuminate. Its small circle of light marks a moment of attention, revealing surface slowly and allowing darkness to retain its depth.": "ఆలయ దృశ్య సంస్కృతిలో దీపం కేవలం వెలిగించదు. దాని చిన్న వెలుగు వలయం దృష్టి క్షణాన్ని గుర్తించి, ఉపరితలాన్ని నెమ్మదిగా చూపిస్తూ చీకటి లోతును నిలుపుతుంది.",
	  "Each entry follows a temple through the materials of its presence: landmark architecture, ritual circulation, carved surfaces, and the human histories carried in its setting. The first archive room opens in Madurai.": "ప్రతి నమోదు ఆలయ ఉనికిలోని పదార్థాలు—ప్రధాన నిర్మాణం, ఆచార కదలిక, చెక్కిన ఉపరితలాలు మరియు పరిసరాల్లో మోసుకొచ్చిన మానవ చరిత్ర—ద్వారా ఆలయాన్ని అనుసరిస్తుంది. మొదటి ఆర్కైవ్ గది మదురైలో తెరుచుకుంటుంది.",
	  "II. Architectural Field Notes": "II. నిర్మాణ ఫీల్డ్ నోట్స్",
	  "III. Sequence and scale": "III. క్రమం మరియు పరిమాణం",
	  "III. The eternal flame": "III. శాశ్వత జ్వాల",
	  "It may have been moved or deleted.": "ఇది తరలించబడి ఉండవచ్చు లేదా తొలగించబడి ఉండవచ్చు.",
	  "Meenakshi is revered as a form of Parvati, while Sundareswarar is Shiva in his local manifestation. Their paired shrines shape the temple’s devotional rhythm and its powerful sense of sacred reciprocity.": "మీనాక్షిని పార్వతి రూపంగా గౌరవిస్తారు; సుందరేశ్వరుడు శివుని స్థానిక రూపం. వారి జత ఆలయాలు ఆలయ భక్తి లయను మరియు పవిత్ర పరస్పరత యొక్క బలమైన భావాన్ని నిర్మిస్తాయి.",
	  "Ornament is not simply surface at Meenakshi. Colour, metal, flowers, textiles, and illuminated stone make ritual visible—reframing the temple’s architecture for each occasion while retaining its enduring spatial order.": "మీనాక్షి ఆలయంలో అలంకరణ కేవలం ఉపరితలం కాదు. రంగు, లోహం, పూలు, వస్త్రాలు మరియు వెలిగిన రాయి ఆచారాన్ని కనిపించేలా చేస్తాయి—ప్రతి సందర్భానికి ఆలయ నిర్మాణానికి కొత్త రూపమిస్తూ దాని శాశ్వత స్థల క్రమాన్ని నిలుపుతాయి.",
	  "Sorry, the page you are looking for doesn't exist.": "క్షమించండి, మీరు వెతుకుతున్న పేజీ లేదు.",
	  "The ceremonial wedding of Meenakshi and Sundareswarar is the emotional high point of the Chithirai festival. It gathers theology, music, dress, procession, and public participation into a single seasonal event.": "మీనాక్షి మరియు సుందరేశ్వరుడి ఆచార వివాహం చిత్తిరై పండుగలో భావోద్వేగ శిఖరం. ఇది తత్వశాస్త్రం, సంగీతం, వస్త్రధారణ, ఊరేగింపు మరియు ప్రజల భాగస్వామ్యాన్ని ఒకే ఋతు వేడుకగా కలుపుతుంది.",
	  "The complex is best read as a sequence of thresholds, towers, circulation, and crafted stone—an architecture continually renewed by use.": "ఈ సముదాయాన్ని గడపలు, గోపురాలు, కదలిక మరియు చెక్కిన రాయి క్రమంగా చదవడం ఉత్తమం—వినియోగంతో నిరంతరం పునరుద్ధరించబడే నిర్మాణం ఇది.",
	  "The experience is architectural as much as spiritual: passages gather into halls, filtered light falls across stone, and the complex unfolds through ceremony, study, commerce, and return.": "ఈ అనుభవం ఆధ్యాత్మికమైనంతే నిర్మాణాత్మకమైనది: మార్గాలు మండపాలుగా కలుస్తాయి, వడపోసిన వెలుగు రాయిపై పడుతుంది మరియు సముదాయం ఆచారం, అధ్యయనం, వాణిజ్యం మరియు తిరుగు ప్రయాణం ద్వారా విప్పుకుంటుంది.",
	  "The experience shifts at the threshold. Light is reduced, sound is gathered, and the elaborate narratives of the exterior fall away in favour of a more concentrated encounter.": "గడప వద్ద అనుభవం మారుతుంది. వెలుగు తగ్గుతుంది, శబ్దం కూడుతుంది మరియు వెలుపలి విస్తృత కథనాలు మరింత కేంద్రీకృతమైన సాక్షాత్కారానికి వెనక్కి తగ్గుతాయి.",
	  "The garbhagriha, literally the “womb chamber,” is the spatial core of a Hindu temple. Its deliberately contained scale gives the structure a gravitational center—one that anchors larger halls, gateways, and routes of circulation.": "గర్భగృహం, అక్షరాలా ‘గర్భ గది’, హిందూ ఆలయపు స్థల కేంద్రం. దాని ఉద్దేశపూర్వకంగా పరిమితమైన పరిమాణం నిర్మాణానికి గురుత్వ కేంద్రాన్ని ఇస్తుంది—పెద్ద మండపాలు, గోపురాలు మరియు కదలిక మార్గాలను ఆధారపరిచే కేంద్రం.",
	  "Listen to this place": "ఈ స్థలం గురించి వినండి",
	  "Stop listening": "వినడాన్ని ఆపండి",
	  Listen: "వినండి",
	  Stop: "ఆపండి",
	  "Voice guidance is not available in this browser": "ఈ బ్రౌజర్‌లో వాయిస్ గైడ్ అందుబాటులో లేదు",
	  "Meenakshi Amman": "మీనాక్షి అమ్మన్",
	  "Madurai, Tamil Nadu": "మదురై, తమిళనాడు",
	  "Konark, Odisha": "కోణార్క్, ఒడిశా",
	  "Rudraprayag, Uttarakhand": "రుద్రప్రయాగ్, ఉత్తరాఖండ్",
	  "Konark Sun Temple": "కోణార్క్ సూర్య ఆలయం",
	  Kedarnath: "కేదార్‌నాథ్",
	  "A vast sacred complex shaped by gopurams, water, processional routes, and the continuing ritual life of Madurai.": "గోపురాలు, నీరు, ఊరేగింపు మార్గాలు మరియు మదురై నిరంతర ఆచార జీవితం రూపుదిద్దిన విస్తారమైన పవిత్ర సముదాయం.",
	  "A monumental thirteenth-century temple known for its sculptural stonework and chariot-like cosmological form.": "శిల్ప రాతి పనితనం మరియు రథంలాంటి విశ్వ రూపానికి ప్రసిద్ధి చెందిన పదమూడవ శతాబ్దపు మహత్తర ఆలయం.",
	  "A high Himalayan shrine whose compact stone architecture is framed by the severe scale of the Garhwal mountains.": "గఢ్వాల్ పర్వతాల మహత్తర విస్తారంతో చుట్టుముట్టబడిన సాంద్రమైన రాతి నిర్మాణం కలిగిన ఎత్తైన హిమాలయ పుణ్యక్షేత్రం.",
	  "A towering gopuram at the Meenakshi Amman Temple in Madurai.": "మదురై మీనాక్షి అమ్మన్ ఆలయంలోని ఎత్తైన గోపురం.",
	  "The stone mass of the Konark Sun Temple under a deep blue night sky.": "గాఢ నీలి రాత్రి ఆకాశం కింద కోణార్క్ సూర్య ఆలయ రాతి విస్తారం.",
	  "Kedarnath Temple set beneath rocky Himalayan slopes.": "రాతి హిమాలయ వాలుల కింద ఉన్న కేదార్‌నాథ్ ఆలయం.",
	};
	const en: Catalog = {};
	const catalogs = { en, hi: { ...hi, ...hiExtra }, te: { ...te, ...teExtra } };
const Context = createContext<{ language: Language; setLanguage: (value: Language) => void; t: (key: string) => string } | null>(null);
export function LanguageProvider({ children }: { children: ReactNode }) { const [language, setLanguageState] = useState<Language>(() => { if (typeof window === "undefined") return "en"; const value = window.localStorage.getItem("eternal-heritage-language"); return value === "hi" || value === "te" ? value : "en"; }); const setLanguage = (value: Language) => setLanguageState(value); useEffect(() => { window.localStorage.setItem("eternal-heritage-language", language); document.documentElement.lang = language; }, [language]); const value = useMemo(() => ({ language, setLanguage, t: (key: string) => catalogs[language][key] ?? key }), [language]); return <Context.Provider value={value}>{children}</Context.Provider>; }
export function useLanguage() { const context = useContext(Context); if (!context) throw new Error("useLanguage must be used within LanguageProvider"); return context; }
